"use client";

import {useEffect,useRef,useState} from "react";

const mechanisms=[
  {tab:"Hip Alignment",title:"Spinal Align™",sub:"Ergonomic relief for tired hips and lower back.",body:"Our natural latex bolster targets the space between your legs to maintain a straight spine while side-sleeping. Draping a leg over it prevents your pelvis from twisting, helping prevent early morning lower back pressure.",image:"https://cdn.shopify.com/s/files/1/0832/5038/1050/files/ChatGPT_Image_Jul_21_2026_06_57_02_PM.png?v=1784631510",alt:"Ergonomic body support illustration"},
  {tab:"Zero Sagging",title:"EverBounce™ Tech",sub:"No more shaking or punching your bolster.",body:"Unlike fiberfill or cotton bolsters that flatten out in the middle when you drape a heavy leg over them, our cylindrical latex core retains its exact density and shape. It rebounds immediately under pressure.",image:"https://cdn.shopify.com/s/files/1/0832/5038/1050/files/ChatGPT_Image_Jul_21_2026_06_57_06_PM.png?v=1784631510",alt:"Latex bolster showing immediate shape recovery"},
  {tab:"Washable Cover",title:"FreshBreathe™",sub:"A cleaner surface for body hugging.",body:"Body pillows naturally absorb body sweat and skin oils overnight. Our latex bolster features a zip-removable, machine-washable cotton cover. Clean your bedding setup with absolute ease to keep surface allergens away.",image:"https://cdn.shopify.com/s/files/1/0832/5038/1050/files/ChatGPT_Image_Jul_21_2026_06_57_10_PM.png?v=1784631509",alt:"Removable and washable bolster protective cover"},
  {tab:"Core Cooling",title:"ThermoMatrix™",sub:"Engineered for breezy night hugging.",body:"Hugging a massive body pillow usually makes you overheat. Our latex core features an open-cell structure that continuously circulates cool room air, translating body heat away from your core on warm nights.",image:"https://cdn.shopify.com/s/files/1/0832/5038/1050/files/ChatGPT_Image_Jul_21_2026_06_57_14_PM.png?v=1784631509",alt:"Airflow channels passing through latex bolster core"}
];

const anatomy=[
  ["Fresh Cotton Shield","Ultra-soft, skin-friendly cotton mesh cover that unzips effortlessly for fast washing and high full-body hygiene.","https://cdn.shopify.com/s/files/1/0832/5038/1050/files/ChatGPT_Image_Jul_21_2026_06_57_18_PM.png?v=1784631509","Fresh cotton shield casing layer"],
  ["Venting Micro-Channels","Thousands of molded open-cell pinholes create consistent ventilation to translate trapped body humidity away rapidly.","https://cdn.shopify.com/s/files/1/0832/5038/1050/files/ChatGPT_Image_Jul_21_2026_06_57_25_PM.png?v=1784631509","Airflow micro-channels grid design"],
  ["Responsive Botanical Core","100% natural latex core that offers immediate body-molding support, relieving deep muscular pressure from night one.","https://cdn.shopify.com/s/files/1/0832/5038/1050/files/ChatGPT_Image_Jul_21_2026_06_57_29_PM.png?v=1784631510","100% pure premium natural latex bolster core"]
];

function FeatureIcon({type}:{type:"shield"|"air"|"spine"|"health"}){
  const common={viewBox:"0 0 24 24",fill:"none",stroke:"currentColor",strokeWidth:1.6,strokeLinecap:"round" as const,strokeLinejoin:"round" as const,"aria-hidden":true};
  if(type==="shield")return <svg {...common}><path d="M12 2 4 6v6c0 5 3.5 9 8 10 4.5-1 8-5 8-10V6l-8-4Z"/><path d="m9 12 2 2 4-4"/></svg>;
  if(type==="air")return <svg {...common}>{[7,12,17].flatMap((x,index)=><g key={index}><path d={`M${x} 4c0 2-2 3-2 5`}/><path d={`M${x} 13c0 2-2 3-2 5`}/></g>)}</svg>;
  if(type==="spine")return <svg {...common}><path d="M12 3v18M8 5h8M8 9h8M8 13h8M8 17h8M8 21h8"/></svg>;
  return <svg {...common}><circle cx="12" cy="12" r="9"/><path d="M12 7v10M7 12h10"/></svg>;
}

export default function BolsterDetails(){
  const [active,setActive]=useState(0);const trusted=useRef<HTMLDivElement>(null);
  useEffect(()=>{const node=trusted.current;if(!node)return;const observer=new IntersectionObserver(([entry])=>{if(entry.isIntersecting){node.classList.add("is-visible");observer.disconnect()}},{threshold:.25});observer.observe(node);return()=>observer.disconnect()},[]);
  return <>
    <section className="hp-support-section"><div className="mdl-trusted" ref={trusted}><div className="mdl-trusted-wrap"><div className="mdl-trusted-content"><div className="mdl-trusted-rating"><span className="mdl-trusted-stars">★★★★★</span><span>Excellent <strong>4.9/5 Rated</strong></span></div><h2 className="mdl-trusted-headline">Full-Body Alignment.<br/>Night After Night.</h2><p className="mdl-trusted-subhead">Wake up without the aches. Our natural latex bolster provides responsive cushioning that supports your body weight, keeping your hips and spine perfectly aligned.</p><div className="mdl-trusted-stats">{[[94,"Relieve Lower Back Tension","Users noticed a huge drop in morning lower back and hip tension within their first week of side-sleeping."],[88,"Less Tossing & Turning","Hugging a supportive bolster naturally anchors your sleep posture, preventing you from constantly shifting."],[91,"Experience Zero Body Heat","Built with an open-cell matrix that actively pushes hot air out, keeping your core cool and sweat-free when hugging it."]].map(([percent,title,description])=><div className="mdl-trusted-stat" key={String(title)}><div className="mdl-trusted-circle"><svg viewBox="0 0 64 64" aria-hidden="true"><circle className="mdl-trusted-circle-bg" cx="32" cy="32" r="27"/><circle className="mdl-trusted-circle-fg" cx="32" cy="32" r="27" style={{"--percent":percent} as React.CSSProperties}/></svg><span>{percent}%</span></div><div><h3>{title}</h3><p>{description}</p></div></div>)}</div></div><div className="mdl-trusted-image"><img src="https://cdn.shopify.com/s/files/1/0832/5038/1050/files/ChatGPT_Image_Jul_21_2026_06_56_58_PM.png?v=1784631510" alt="MD Latex Bolster side sleeper comfort"/></div></div></div></section>
    <section className="mdl-tabs"><div className="mdl-tabs-wrap"><div className="mdl-tabs-nav" role="tablist" aria-label="Bolster mechanisms">{mechanisms.map((item,index)=><button type="button" key={item.tab} className={`mdl-tab-btn ${active===index?"is-active":""}`} role="tab" aria-selected={active===index} onClick={()=>setActive(index)}>{item.tab}</button>)}</div><div className="mdl-tabs-content">{mechanisms.map((item,index)=><div key={item.tab} className={`mdl-tab-panel ${active===index?"is-active":""}`} role="tabpanel" hidden={active!==index}><div className="mdl-tab-text"><h3 className="mdl-tab-headline">{item.title}</h3><p className="mdl-tab-subhead">{item.sub}</p><p className="mdl-tab-body">{item.body}</p></div><div className="mdl-tab-image"><img src={item.image} alt={item.alt}/></div></div>)}</div></div></section>
    <section className="hp-comparison"><div className="hp-comparison-wrap"><div className="hp-comparison-copy"><h2>Why Choose MD<br/>Latex Instead?</h2><p>Real full-body comfort. Real orthopedic support. Long-lasting, cooling sleep quality.</p></div><div className="hp-table" role="table" aria-label="MD Latex bolster compared with traditional bolsters"><div className="hp-row hp-head" role="row"><span></span><b>MD<br/>Latex</b><strong>Others</strong></div>{["Stable full-body support","Cooling air circulation","Maintains hip alignment","Long-lasting shape recovery","Naturally hygienic core"].map(label=><div className="hp-row" role="row" key={label}><span>{label}</span><b aria-label="Included">✓</b><strong aria-label="Not included">×</strong></div>)}</div></div></section>
    <section className="hp-features"><div className="hp-features-card"><h2>The Orthopedic Bolster Standard</h2><div className="hp-features-grid">{[["shield","Pure & Skin-Safe","Zero toxic off-gassing or harsh synthetics against your body"],["air","Sweat-Free Nights","Actively vents trapped moisture and body heat away from the skin"],["spine","Spinal Decompression","Ergonomically balances your leg and arm weight to ease hip tension"],["health","Microbe Defending","Inherent botanical properties stop mold and dust mites instantly"]].map(([type,title,description])=><article key={title}><i><FeatureIcon type={type as "shield"|"air"|"spine"|"health"}/></i><h3>{title}</h3><p>{description}</p></article>)}</div></div></section>
    <section className="mdl-sleepers"><div className="mdl-sleepers-wrap"><header><h2>Anatomy of Full-Body Comfort</h2><p>Every layer engineered perfectly from clean plant-based materials to deliver crisp, stress-free body recovery.</p></header><div className="mdl-sleepers-grid">{anatomy.map(([title,description,image,alt])=><article key={title}><img src={image} alt={alt}/><h3>{title}</h3><p>{description}</p></article>)}</div></div></section>
    <section className="mdl-pillow-matrix"><div className="mdl-matrix-wrap"><div><h2>Why Traditional Bolsters Mismatch Your Body</h2><p>Standard down-feather or loose cotton bolsters slump out of form within an hour, forcing your hips and spine out of alignment. MD Latex ensures stable orthopedic full-body lift across every key comfort metric.</p>{[["Stable Body Support:"," Holds its cylindrical shape completely, even when draping a heavy leg over it."],["Active Air Circulation:"," Pushes body heat out through physical air pathways to keep your skin dry."],["Clinical Posture Control:"," Provides the necessary leg elevation to keep side sleepers correctly aligned."]].map(([lead,text])=><div className="mdl-matrix-bullet" key={lead}><span>✓</span><p><strong>{lead}</strong>{text}</p></div>)}</div><div className="mdl-matrix-image"><img src="https://cdn.shopify.com/s/files/1/0832/5038/1050/files/34.png?v=1785149842" alt="MD Latex Bolster versus traditional bolster performance comparison"/></div></div></section>
  </>;
}
