"use client";

import {useEffect,useRef,useState} from "react";

const mechanisms=[
  {tab:"Broad Support",title:"High Loft Elevation™",sub:"Premium support for side sleepers & broader shoulders.",body:"Our natural latex high pillow features an elevated, thick profile designed specifically to fill the gap between the mattress and your head. It keeps side sleepers' spines perfectly straight without bottoming out.",image:"/images/md_latex_high_pillow_mechanism_broad_support.webp",alt:"Ergonomic neck support illustration"},
  {tab:"Zero Sagging",title:"EverBounce™ Tech",sub:"No more shaking or punching your pillow.",body:"Unlike fiberfill or feather pillows that flatten into pancakes, our thick natural latex core retains its tall, supportive loft night after night. It rebounds immediately under pressure, meaning zero hollow spots.",image:"/images/md_latex_high_pillow_mechanism_zero_sagging.webp",alt:"Latex pillow showing immediate shape recovery"},
  {tab:"Washable Cover",title:"FreshBreathe™",sub:"A cleaner surface for clear skin.",body:"Pillows are magnets for hair oils and loose skin cells. Our tall latex pillow features a zip-removable, machine-washable cotton cover. Clean your pillowcase setup with absolute ease to keep surface allergens away.",image:"/images/md_latex_high_pillow_mechanism_washable_cover.webp",alt:"Removable and washable pillow protective cover"},
  {tab:"Head Cooling",title:"ThermoMatrix™",sub:"Engineered for breezy night comfort.",body:"Memory foam traps heat, but our thick latex core features an open-cell structure with vertical pinholes that continuously circulates cool room air. Warm air translates away from your face, providing a cool resting spot.",image:"/images/md_latex_high_pillow_mechanism_head_cooling.webp",alt:"Airflow channels passing through latex pillow core"}
];

const faqs=[
  ["Is a natural latex pillow better than memory foam?","Yes, especially for your neck. Natural latex offers an instant, buoyant response that lifts your head rather than letting it sink in like memory foam. It also features superior open-cell breathability, so it doesn't trap facial heat or create that claustrophobic, ‘stuck’ feeling."],
  ["How long does a natural latex pillow last?","While standard fiber or down pillows flatten out within a year, a high-quality natural latex pillow easily maintains its spring, height, and shape for 3 to 5 years. It is highly resilient and completely immune to clumping or sagging."],
  ["Is a latex pillow suitable for hot sleepers or tropical weather?","Absolutely. Our latex pillows are engineered with an advanced AirFlow pinhole matrix. This structural design allows fresh air to circulate constantly underneath your head, pushing out hot ambient air and moisture so you stay crisp all night."],
  ["Does a latex pillow help with neck pain and cervical support?","Yes. It provides proactive cervical support by filling the natural gap between your neck and the mattress. By keeping your spine in a straight, neutral line, it unloads pressure from your upper shoulders and stops morning stiffness before it starts."]
];

const testimonials=[
  {title:"No More Neck Knots",body:"I used to wake up every single morning with a stiff neck and tight shoulders. Switching to this latex pillow changed everything on night one. It lifts my head perfectly and never goes flat."},
  {title:"Stays Amazingly Cool",body:"Living in Malaysia, regular pillows always turn into hot sponges by midnight. This latex one stays incredibly breezy. No sweat, no constant pillow-flipping. Absolutely worth every cent."}
];

function OrthopedicIcon({type}:{type:"shield"|"droplet"|"alignment"|"microbe"}){
  const common={viewBox:"0 0 48 48",fill:"none",stroke:"currentColor",strokeWidth:2,strokeLinecap:"round" as const,strokeLinejoin:"round" as const,"aria-hidden":true};
  if(type==="shield")return <svg {...common}><path d="M24 5 39 11v11c0 9.7-6.1 17-15 21-8.9-4-15-11.3-15-21V11L24 5Z"/><path d="m17 24 4.5 4.5L31.5 18"/></svg>;
  if(type==="droplet")return <svg {...common}><path d="M24 5S12 18.8 12 29a12 12 0 0 0 24 0C36 18.8 24 5 24 5Z"/><path d="M19 34c1.4 1.6 3 2.3 5 2.3" opacity=".65"/></svg>;
  if(type==="alignment")return <svg {...common}><path d="M24 6v36M17 13l7-7 7 7M17 35l7 7 7-7"/><path d="M13 19h22M13 24h22M13 29h22" opacity=".72"/></svg>;
  return <svg {...common}><circle cx="24" cy="24" r="17"/><path d="M24 16v16M16 24h16"/></svg>;
}

export default function HighPillowDetails(){
  const [active,setActive]=useState(0);const [testimonial,setTestimonial]=useState(0);const [slideDirection,setSlideDirection]=useState<"left"|"right">("right");const trusted=useRef<HTMLElement>(null);const testimonialTouchX=useRef(0);
  const moveTestimonial=(direction:"left"|"right")=>{setSlideDirection(direction);setTestimonial(value=>(value+(direction==="right"?1:-1)+testimonials.length)%testimonials.length)};
  const swipeTestimonial=(end:number)=>{const delta=end-testimonialTouchX.current;if(Math.abs(delta)>40)moveTestimonial(delta<0?"right":"left")};
  useEffect(()=>{const node=trusted.current;if(!node)return;const observer=new IntersectionObserver(([entry])=>{if(entry.isIntersecting){node.classList.add("is-visible");observer.disconnect()}},{threshold:.25});observer.observe(node);return()=>observer.disconnect()},[]);
  return <>
    <section className="hp-product-extras" aria-label="High Pillow details"><div className="hp-faqs">{faqs.map(([question,answer])=><details open key={question}><summary><i>✓</i>{question}<span>⌃</span></summary><p>{answer}</p></details>)}</div><div className="hp-testimonials" aria-label="Customer testimonials"><blockquote><div><h3>No More Neck Knots</h3><span>〈　〉</span></div><p>I used to wake up every single morning with a stiff neck and tight shoulders. Switching to this latex pillow changed everything on night one. It lifts my head perfectly and never goes flat.</p><footer>★★★★★</footer></blockquote><blockquote><div><h3>Stays Amazingly Cool</h3><span>〈　〉</span></div><p>Living in Malaysia, regular pillows always turn into hot sponges by midnight. This latex one stays incredibly breezy. No sweat, no constant pillow-flipping. Absolutely worth every cent.</p><footer>★★★★★</footer></blockquote></div></section>
    <section className="hp-testimonials hp-testimonials-featured" aria-label="Customer testimonials" onTouchStart={event=>testimonialTouchX.current=event.touches[0].clientX} onTouchEnd={event=>swipeTestimonial(event.changedTouches[0].clientX)}><button type="button" className="hp-testimonial-arrow hp-testimonial-prev" onClick={()=>moveTestimonial("left")} aria-label="Previous testimonial">‹</button><div className={`hp-testimonial-slide slide-${slideDirection}`} key={testimonial}><blockquote><h3>{testimonials[testimonial].title}</h3><p>{testimonials[testimonial].body}</p><footer>★★★★★</footer></blockquote></div><button type="button" className="hp-testimonial-arrow hp-testimonial-next" onClick={()=>moveTestimonial("right")} aria-label="Next testimonial">›</button><div className="hp-testimonial-dots">{testimonials.map((item,index)=><button type="button" key={item.title} className={index===testimonial?"is-active":""} onClick={()=>{setSlideDirection(index>testimonial?"right":"left");setTestimonial(index)}} aria-label={`Show testimonial: ${item.title}`}/>)}</div></section>
    <section className="hp-support-section"><div className="mdl-trusted" ref={trusted}><div className="mdl-trusted-wrap"><div className="mdl-trusted-content"><div className="mdl-trusted-rating"><span className="mdl-trusted-stars">★★★★★</span><span>Excellent <strong>4.9/5 Rated</strong></span></div><h2 className="mdl-trusted-headline">High-Profile Support.<br/>Night After Night.</h2><p className="mdl-trusted-subhead">Wake up without the knots. Our natural latex high pillow provides thick, responsive cushioning that elevates your head and aligns your spine perfectly for side and larger-framed sleepers.</p><div className="mdl-trusted-stats">{[[94,"Relieve Neck Stiffness","Users noticed a huge drop in morning upper neck and shoulder tension within their first week of proper elevation."],[88,"Less Tossing & Turning","The instant-rebound properties of latex adapt dynamically as you change positions, preventing you from sinking in."],[91,"Experience Zero Head Heat","Built with an open-cell matrix that actively pushes hot air out, keeping your head crisp and sweat-free."]].map(([percent,title,desc])=><div className="mdl-trusted-stat" key={String(title)}><div className="mdl-trusted-circle"><svg viewBox="0 0 64 64" aria-hidden="true"><circle className="mdl-trusted-circle-bg" cx="32" cy="32" r="27"/><circle className="mdl-trusted-circle-fg" cx="32" cy="32" r="27" style={{"--percent":percent} as React.CSSProperties}/></svg><span>{percent}%</span></div><div><h3>{title}</h3><p>{desc}</p></div></div>)}</div></div><div className="mdl-trusted-image"><img src="/images/md_latex_high_pillow_high_profile_support.webp" alt="MD Latex High Pillow front profile"/></div></div></div></section>
    <section className="mdl-tabs" id="mdl-pillow-tabs-section"><div className="mdl-tabs-wrap"><div className="mdl-tabs-nav" role="tablist" aria-label="High Pillow mechanisms">{mechanisms.map((item,index)=><button key={item.tab} className={`mdl-tab-btn ${active===index?"is-active":""}`} role="tab" aria-selected={active===index} aria-controls={`mechanism-${index}`} onClick={()=>setActive(index)}>{item.tab}</button>)}</div><div className="mdl-tabs-content">{mechanisms.map((item,index)=><div key={item.tab} id={`mechanism-${index}`} className={`mdl-tab-panel ${active===index?"is-active":""}`} role="tabpanel" hidden={active!==index}><div className="mdl-tab-text"><h3 className="mdl-tab-headline">{item.title}</h3><p className="mdl-tab-subhead">{item.sub}</p><p className="mdl-tab-body">{item.body}</p></div><div className="mdl-tab-image"><img src={item.image} alt={item.alt}/></div></div>)}</div></div></section>
    <section className="hp-comparison"><div className="hp-comparison-wrap"><div className="hp-comparison-copy"><h2>Why Choose MD<br/>Latex Instead?</h2><p>Real cervical comfort. Real neck support. Long-lasting, cooling sleep quality.</p></div><div className="hp-table" role="table" aria-label="MD Latex compared with traditional pillows"><div className="hp-row hp-head" role="row"><span></span><b>MD<br/>Latex</b><strong>Others</strong></div>{["Cervical Neck Support","Tropical Heat Regulation","Density Longevity","Allergy & Hygiene Defense","Initial Touch Feel"].map(label=><div className="hp-row" role="row" key={label}><span>{label}</span><b aria-label="Included">✓</b><strong aria-label="Not included">×</strong></div>)}</div></div></section>
    <section className="hp-features"><div className="hp-features-card"><h2>The Orthopedic Pillow Standard</h2><div className="hp-features-grid"><article><i><OrthopedicIcon type="shield"/></i><h3>Pure &amp; Skin-Safe</h3><p>Zero toxic off-gassing or harsh synthetics hitting your face</p></article><article><i><OrthopedicIcon type="droplet"/></i><h3>Sweat-Free Nights</h3><p>Actively vents trapped moisture and heat away from the skin</p></article><article><i><OrthopedicIcon type="alignment"/></i><h3>High-Loft Alignment</h3><p>Elevates your head to effortlessly align broader shoulders and relieve tension</p></article><article><i><OrthopedicIcon type="microbe"/></i><h3>Microbe Defending</h3><p>Inherent botanical properties stop mold and dust mites instantly</p></article></div></div></section>
    <section className="mdl-sleepers"><div className="mdl-sleepers-wrap"><header><h2>Anatomy of Premium Support</h2><p>Every layer engineered perfectly from clean plant-based materials to deliver crisp, stress-free sleep.</p></header><div className="mdl-sleepers-grid">{[['Fresh Cotton Shield','Ultra-soft, skin-friendly cotton mesh cover that unzips effortlessly for fast washing and high facial hygiene.','/images/md_latex_high_pillow_anatomy_fresh_cotton_shield.webp','Fresh cotton shield casing layer'],['Venting Micro-Channels','Thousands of molded open-cell pinholes create consistent ventilation to translate head humidity away rapidly.','/images/md_latex_high_pillow_anatomy_venting_micro_channels.webp','Airflow micro-channels grid design'],['Responsive Botanical Core','100% natural latex core that offers immediate body-molding lift, relieving deep muscular pressure from night one.','/images/md_latex_high_pillow_anatomy_responsive_botanical_core.webp','100% pure premium natural latex pillow core']].map(([title,desc,image,alt])=><article key={title}><img src={image} alt={alt}/><h3>{title}</h3><p>{desc}</p></article>)}</div></div></section>
    <section className="mdl-pillow-matrix"><div className="mdl-matrix-wrap"><div><h2>Why Traditional Pillows Mismatch Your Body</h2><p>Standard down-feather or loose cotton pillows slump out of form within an hour, forcing your cervical posture out of alignment. The MD Latex High Pillow ensures stable, thick orthopedic lift across every key comfort metric.</p>{[["Stable High Profile Support:"," Holds its tall physical shape completely without requiring constant midnight fluffing."],["Active Air Circulation:"," Pushes heat out through physical air pathways to keep your skin dry."],["Clinical Posture Control:"," Provides the necessary elevation to keep side sleepers correctly aligned."]].map(([lead,text])=><div className="mdl-matrix-bullet" key={lead}><span>✓</span><p><strong>{lead}</strong>{text}</p></div>)}</div><div className="mdl-matrix-image"><img src="/images/md_latex_high_pillow_productpicture8.webp" alt="MD Latex versus competitor traditional pillow performance checklist comparison chart"/></div></div></section>
  </>
}
