import Link from "next/link";
import { Footer, Header, ContactForm, Faq } from "./site-components";
const categoryImages=["https://mdlatex.com.my/cdn/shop/collections/1_f430e1ac-d540-4a5c-9fdf-c44aaa4ef0bc.png?v=1784705454&width=1500","https://mdlatex.com.my/cdn/shop/collections/2_586fe363-0b3d-42bd-a175-5305eba32605.png?v=1784705456&width=1500","https://mdlatex.com.my/cdn/shop/collections/3_85b736eb-70f5-4f64-a8b0-2fdcedfa9874.png?v=1784705452&width=1500"];
export default function Home(){return <><Header/><main>
<section className="hero" style={{backgroundImage:"linear-gradient(#0006,#0006),url('https://cdn.shopify.com/s/files/1/0832/5038/1050/files/79a1e911-995e-4ddc-aaee-97d85e588e2c.jpg?v=1779780103')"}}><div><h1>Premium Latex For Better Living</h1><p>Experience the perfect balance of comfort, support and durability with our 100% natural latex products.</p><Link className="button light" href="/collections/all">Shop All</Link></div></section>
<section className="section categories"><h2>Find the Perfect Fit for Your Needs</h2><div className="category-grid">{[['Mattresses','mattresses'],['Pillows','pillows'],['Baby & Kids','baby-kids']].map((c,i)=><Link href={`/collections/${c[1]}`} className="category" key={c[1]}><img src={categoryImages[i]} alt={c[0]}/><span>{c[0]}</span></Link>)}</div></section>
<section className="benefits"><div className="section"><p className="eyebrow">Why Choose MD Latex M Sdn. Bhd.?</p><h2>Quality You Can Trust</h2><div className="benefit-grid">{[['◇','100% Natural Latex','Made from the finest natural latex materials'],['✓','Safe & Certified','Certified safe for your family'],['◌','Breathable & Cool','Natural ventilation for cool and comfortable sleep'],['↗','Durable & Supportive','Built to last with excellent elasticity and support'],['♧','Eco Friendly','Sustainable production for a better tomorrow'],['✦','Hypoallergenic','Naturally resistant to dust mites and allergens']].map(x=><article key={x[1]}><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></div></section>
<section className="story section"><div className="story-image" style={{backgroundImage:"url('https://cdn.shopify.com/s/files/1/0832/5038/1050/files/rubber-home.jpg?v=1779184522')"}}/><div><p className="eyebrow">About Us</p><h2>Crafted with Nature,<br/>Made for You</h2><p>With years of experience in latex goods, MD Latex M Sdn. Bhd. is committed to delivering premium quality latex products that improve your sleep and enhance your lifestyle.</p><div className="stats"><span><b>10+</b>Years Experience</span><span><b>100,000+</b>Happy Customers</span><span><b>100%</b>Quality Guarantee</span></div><Link href="/pages/about-us" className="text-link">Discover our story →</Link></div></section>
<section className="testimonials"><div className="section"><p className="eyebrow">What Our Customers Say</p><h2>Trusted by Thousands Nationwide</h2><div className="quote-grid">{[['“I’ve suffered from lower back pain for years. Since switching to this latex mattress, my mornings are completely pain-free.”','Sarah L.','Kuala Lumpur, MY'],['“Sangat selesa dan sejuk! Cuaca dekat Malaysia ni panas, tapi tidur atas tilam ni tak berpeluh langsung.”','Ahmad Fadhil','Selangor, MY'],['“质量非常好，完全没有刺鼻的化学味道。乳胶的支撑力也很够，第二天起来不会腰酸背痛。”','Wong C.H.','Penang, MY']].map(q=><blockquote key={q[1]}><div className="stars">★★★★★</div><p>{q[0]}</p><footer><b>{q[1]}</b><small>{q[2]}</small></footer></blockquote>)}</div></div></section>
<section className="section home-contact"><Faq/><ContactForm title="Have questions? Contact us here"/></section>
</main><Footer/></>}
