import Link from "next/link";
import { Footer, Header, ContactForm, LocationFaq, Reviews } from "./site-components";
const categoryImages=["https://mdlatex.com.my/cdn/shop/collections/1_f430e1ac-d540-4a5c-9fdf-c44aaa4ef0bc.png?v=1784705454&width=1500","https://mdlatex.com.my/cdn/shop/collections/2_586fe363-0b3d-42bd-a175-5305eba32605.png?v=1784705456&width=1500","https://mdlatex.com.my/cdn/shop/collections/3_85b736eb-70f5-4f64-a8b0-2fdcedfa9874.png?v=1784705452&width=1500"];
export default function Home(){return <><Header/><main>
<section className="mdl-hero-section"><img className="mdl-hero-bg-img" src="https://cdn.shopify.com/s/files/1/0832/5038/1050/files/79a1e911-995e-4ddc-aaee-97d85e588e2c.jpg?v=1779780103" alt="Premium Natural Latex Bedding"/><div className="mdl-hero-overlay"><div className="mdl-hero-content"><h1>Premium Latex For Better Living</h1><p>Experience the perfect balance of comfort, support and durability with our 100% natural latex products.</p><Link className="mdl-hero-btn" href="/collections/all">Shop All</Link></div></div></section>
<section className="section categories"><h2>Find the Perfect Fit for Your Needs</h2><div className="category-grid">{[['Mattresses','mattresses'],['Pillows','pillows'],['Baby & Kids','baby-kids']].map((c,i)=><Link href={`/collections/${c[1]}`} className="category" key={c[1]}><img src={categoryImages[i]} alt={c[0]}/><span>{c[0]}</span></Link>)}</div></section>
<section className="mdl-features"><div className="mdl-features-card"><div className="mdl-features-header"><p className="mdl-features-eyebrow">Why Choose MD Latex M Sdn. Bhd.?</p><h2 className="mdl-features-title">Quality You Can Trust</h2></div><div className="mdl-features-grid">
<div className="mdl-feature-item"><div className="mdl-feature-icon"><svg viewBox="0 0 24 24"><path d="M11 20A7 7 0 0 1 4 13c0-5 4-9 16-9 0 11-4 16-9 16z"/><path d="M4 20c2-6 6-10 12-12"/></svg></div><h4 className="mdl-feature-title">100% Natural Latex</h4><p className="mdl-feature-desc">Made from the finest natural latex materials</p></div>
<div className="mdl-feature-item"><div className="mdl-feature-icon"><svg viewBox="0 0 24 24"><path d="M12 2L4 6v6c0 5 3.5 9 8 10 4.5-1 8-5 8-10V6l-8-4z"/><polyline points="9 12 11 14 15 10"/></svg></div><h4 className="mdl-feature-title">Safe &amp; Certified</h4><p className="mdl-feature-desc">Certified safe for your family</p></div>
<div className="mdl-feature-item"><div className="mdl-feature-icon"><svg viewBox="0 0 24 24"><path d="M7 4c0 2-2 3-2 5"/><path d="M12 4c0 2-2 3-2 5"/><path d="M17 4c0 2-2 3-2 5"/><path d="M7 13c0 2-2 3-2 5"/><path d="M12 13c0 2-2 3-2 5"/><path d="M17 13c0 2-2 3-2 5"/></svg></div><h4 className="mdl-feature-title">Breathable &amp; Cool</h4><p className="mdl-feature-desc">Natural ventilation for cool and comfortable sleep</p></div>
<div className="mdl-feature-item"><div className="mdl-feature-icon"><svg viewBox="0 0 24 24"><line x1="12" y1="3" x2="12" y2="21"/><path d="M8 5h8"/><path d="M8 9h8"/><path d="M8 13h8"/><path d="M8 17h8"/><path d="M8 21h8"/></svg></div><h4 className="mdl-feature-title">Durable &amp; Supportive</h4><p className="mdl-feature-desc">Built to last with excellent elasticity and support</p></div>
<div className="mdl-feature-item"><div className="mdl-feature-icon"><svg viewBox="0 0 24 24"><path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78L12 21.23l8.84-8.84a5.5 5.5 0 0 0 0-7.78z"/><path d="M9 11c0-2 1.5-3.5 3-3.5"/></svg></div><h4 className="mdl-feature-title">Eco Friendly</h4><p className="mdl-feature-desc">Sustainable production for a better tomorrow</p></div>
<div className="mdl-feature-item"><div className="mdl-feature-icon"><svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="9"/><line x1="12" y1="7" x2="12" y2="17"/><line x1="7" y1="12" x2="17" y2="12"/></svg></div><h4 className="mdl-feature-title">Hypoallergenic</h4><p className="mdl-feature-desc">Naturally resistant to dust mites and allergens</p></div>
</div></div></section>
<section className="mdl-about"><div className="mdl-about-wrap"><div className="mdl-about-image"><img src="https://cdn.shopify.com/s/files/1/0832/5038/1050/files/rubber-home.jpg?v=1779184522" alt="MD Latex — natural latex tapping"/></div><div className="mdl-about-content"><p className="mdl-about-eyebrow">About Us</p><h2 className="mdl-about-headline">Crafted with Nature,<br/>Made for You</h2><p className="mdl-about-description">With years of experience in latex goods, MD Latex M Sdn. Bhd. is committed to delivering premium quality latex products that improve your sleep and enhance your lifestyle.</p><div className="mdl-about-stats"><div><p className="mdl-about-stat-number">10+</p><p className="mdl-about-stat-label">Years Experience</p></div><div><p className="mdl-about-stat-number">100,000+</p><p className="mdl-about-stat-label">Happy Customers</p></div><div><p className="mdl-about-stat-number">100%</p><p className="mdl-about-stat-label">Quality Guarantee</p></div></div></div></div></section>
<Reviews/><LocationFaq/><section className="section"><ContactForm title="Have questions? Contact us here"/></section>
</main><Footer/></>}
