import Link from "next/link";
import { Footer, Header, ContactForm, LocationFaq, Reviews } from "./site-components";
const categoryImages=["https://mdlatex.com.my/cdn/shop/collections/1_f430e1ac-d540-4a5c-9fdf-c44aaa4ef0bc.png?v=1784705454&width=1500","https://mdlatex.com.my/cdn/shop/collections/2_586fe363-0b3d-42bd-a175-5305eba32605.png?v=1784705456&width=1500","https://mdlatex.com.my/cdn/shop/collections/3_85b736eb-70f5-4f64-a8b0-2fdcedfa9874.png?v=1784705452&width=1500"];
export default function Home(){return <><Header/><main>
<section className="mdl-hero-section"><img className="mdl-hero-bg-img" src="https://cdn.shopify.com/s/files/1/0832/5038/1050/files/79a1e911-995e-4ddc-aaee-97d85e588e2c.jpg?v=1779780103" alt="Premium Natural Latex Bedding"/><div className="mdl-hero-overlay"><div className="mdl-hero-content"><h1>Premium Latex For Better Living</h1><p>Experience the perfect balance of comfort, support and durability with our 100% natural latex products.</p><Link className="mdl-hero-btn" href="/collections/all">Shop All</Link></div></div></section>
<section className="section categories"><h2>Find the Perfect Fit for Your Needs</h2><div className="category-grid">{[['Mattresses','mattresses'],['Pillows','pillows'],['Baby & Kids','baby-kids']].map((c,i)=><Link href={`/collections/${c[1]}`} className="category" key={c[1]}><img src={categoryImages[i]} alt={c[0]}/><span>{c[0]}</span></Link>)}</div></section>
<section className="benefits"><div className="section"><p className="eyebrow">Why Choose MD Latex M Sdn. Bhd.?</p><h2>Quality You Can Trust</h2><div className="benefit-grid">{[['◇','100% Natural Latex','Made from the finest natural latex materials'],['✓','Safe & Certified','Certified safe for your family'],['◌','Breathable & Cool','Natural ventilation for cool and comfortable sleep'],['↗','Durable & Supportive','Built to last with excellent elasticity and support'],['♧','Eco Friendly','Sustainable production for a better tomorrow'],['✦','Hypoallergenic','Naturally resistant to dust mites and allergens']].map(x=><article key={x[1]}><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></div></section>
<section className="mdl-about"><div className="mdl-about-wrap"><div className="mdl-about-image"><img src="https://cdn.shopify.com/s/files/1/0832/5038/1050/files/rubber-home.jpg?v=1779184522" alt="MD Latex — natural latex tapping"/></div><div className="mdl-about-content"><p className="mdl-about-eyebrow">About Us</p><h2 className="mdl-about-headline">Crafted with Nature,<br/>Made for You</h2><p className="mdl-about-description">With years of experience in latex goods, MD Latex M Sdn. Bhd. is committed to delivering premium quality latex products that improve your sleep and enhance your lifestyle.</p><div className="mdl-about-stats"><div><p className="mdl-about-stat-number">10+</p><p className="mdl-about-stat-label">Years Experience</p></div><div><p className="mdl-about-stat-number">100,000+</p><p className="mdl-about-stat-label">Happy Customers</p></div><div><p className="mdl-about-stat-number">100%</p><p className="mdl-about-stat-label">Quality Guarantee</p></div></div></div></div></section>
<Reviews/><LocationFaq/><section className="section"><ContactForm title="Have questions? Contact us here"/></section>
</main><Footer/></>}
