"use client";
import Link from "next/link";import {useRef,useState} from "react";
const logoUrl="https://cdn.shopify.com/s/files/1/0832/5038/1050/files/mdlatex-logo.png";
export function Header(){const[open,setOpen]=useState(false);const[sub,setSub]=useState(false);return <><div className="trust">✦ ✦ ✦ ✦ ✦ <b>Trusted by 100,000+</b></div><header><Link className="brand-logo" href="/"><img src={logoUrl} alt="MD Latex — 100% Natural Latex Foam"/></Link><nav><Link href="/">Home</Link><span className="shop">Shop All <i>⌄</i><div><Link href="/collections/all">Shop All</Link><Link href="/collections/mattresses">Mattresses</Link><Link href="/collections/pillows">Pillows</Link><Link href="/collections/baby-kids">Baby &amp; Kids</Link></div></span><Link href="/pages/about-us">About Us</Link><Link href="/pages/contact">Contact</Link></nav><div className="actions"><button aria-label="Search">⌕</button><button aria-label="Account">♙</button><button aria-label="Cart">▢<sup>0</sup></button><button className="menu" onClick={()=>{setOpen(true);setSub(false)}} aria-label="Open menu">☰</button></div></header>{open&&<><button className="drawer-shade" onClick={()=>setOpen(false)} aria-label="Close menu backdrop"/><aside className="mobile-drawer"><div className="drawer-head"><button onClick={()=>sub?setSub(false):setOpen(false)} aria-label={sub?'Back to menu':'Close menu'}>{sub?'←':'×'}</button><Link href="/" onClick={()=>setOpen(false)}><img src={logoUrl} alt="MD Latex — 100% Natural Latex Foam"/></Link><div><button aria-label="Search">⌕</button><button aria-label="Cart">♧</button></div></div>{sub?<div className="drawer-sub"><button onClick={()=>setSub(false)}>← <span>Shop All</span></button><Link href="/collections/mattresses">Mattresses</Link><Link href="/collections/pillows">Pillows</Link><Link href="/collections/baby-kids">Baby &amp; Kids</Link></div>:<div className="drawer-links"><Link className="active" href="/" onClick={()=>setOpen(false)}>Home</Link><button onClick={()=>setSub(true)}><span>Shop All</span><b>→</b></button><Link href="/pages/about-us">About Us</Link><Link href="/pages/contact">Contact</Link></div>}</aside></>}</>}
export function Footer(){return <footer className="footer"><div className="footer-inner"><div><h3>Support Links</h3><Link href="/pages/about-us">About Us</Link><Link href="/pages/contact">Contact Us</Link></div><div className="footer-brand"><Link className="footer-logo" href="/"><img src={logoUrl} alt="MD Latex — 100% Natural Latex Foam"/></Link><h3>Malaysia&apos;s Trusted Latex Brand</h3><p>Crafting premium natural latex products for better sleep, since day one.</p></div></div><div className="copyright">© 2026, MD Latex <span>Privacy policy</span></div></footer>}
export function ContactForm({title="Send Us A Message"}:{title?:string}){return <section className="form-wrap"><h2>{title}</h2><p>Fill in the form and our team will get back to you as soon as possible.</p><form onSubmit={e=>e.preventDefault()}><div><input aria-label="Name" placeholder="Name"/><input aria-label="Email" type="email" placeholder="Email *"/></div><input aria-label="Phone number" placeholder="Phone number"/><textarea aria-label="Comment" placeholder="Comment" rows={6}/><button className="button">Send</button></form></section>}
const faqs=[['Do you accept custom sizes and shapes?','Yes, we specialise in custom sizes and shapes to suit your specific needs. Whether it’s a non-standard mattress dimension or a tailored pillow shape, simply share your specifications with our team and we’ll prepare a quotation and lead time for you.'],['Can I request for product details or samples?','Of course. We’re happy to share full product specifications, certifications, and material details. Samples are available upon request for serious enquiries.'],['Do you supply in bulk or accept OEM orders?','Yes, we work with retailers, distributors, hotels, and private label partners worldwide. We accept bulk orders and offer full OEM services.'],['Where are your products made?','All our products are proudly manufactured in Malaysia at our HQ in Batu Caves, Selangor.'],['How long does it take to get a response?','We aim to reply to all enquiries within 24 hours on business days (Mon – Fri).']];
export function Faq(){return <section className="faq"><h3>Frequently Asked Questions</h3>{faqs.map((f,i)=><details key={f[0]} open={i===0}><summary><b>MD</b>{f[0]}<span>⌄</span></summary><p>{f[1]}</p></details>)}</section>}
const reviews=[
['S','Sarah L.','Kuala Lumpur, MY',"I've suffered from lower back pain for years. Since switching to this latex mattress, my mornings are completely pain-free. The support is incredible, definitely worth every single ringgit."],
['A','Ahmad Fadhil','Selangor, MY','Sangat selesa dan sejuk! Cuaca dekat Malaysia ni panas, tapi tidur atas tilam ni tak berpeluh langsung. Servis penghantaran pun laju dan customer service sangat membantu.'],
['W','Wong C.H.','Penang, MY','质量非常好，完全没有刺鼻的化学味道。买给家里的小孩睡特别安心，乳胶的支撑力也很够，第二天起来不会腰酸背痛，强推！'],
['M','Michael T.','Johor Bahru, MY','The cervical pillows are an absolute game changer. No more stiff neck when I wake up. You can really feel the difference in the density compared to normal memory foam.'],
['N','Nurul Ain','Melaka, MY','Beli tilam ni untuk mak kat kampung, dia cakap sedap sangat pakai. Memang kualiti premium, tahan lama dan tak tenggelam. Bangga produk buatan Malaysia standard antarabangsa.'],
['L','Lim K.S.','Klang, MY','用了一年多，完全没有塌陷的问题。比起以前买的其他牌子，这个纯天然乳胶的透气度和弹性真的好太多了，性价比极高。']];
export function Reviews(){const slider=useRef<HTMLDivElement>(null);const move=(dir:number)=>{const card=slider.current?.querySelector<HTMLElement>('.mdl-rev-card');slider.current?.scrollBy({left:dir*((card?.offsetWidth||380)+24),behavior:'smooth'})};return <section className="mdl-reviews-sec"><div className="mdl-reviews-wrap"><div className="mdl-rev-header mdl-anim-rev"><p>What Our Customers Say</p><h2>Trusted by Thousands Nationwide</h2></div><div className="mdl-rev-slider mdl-anim-rev" ref={slider}>{reviews.map(r=><article className="mdl-rev-card" key={r[1]}><div className="mdl-rev-stars">★★★★★</div><p className="mdl-rev-text">&quot;{r[3]}&quot;</p><div className="mdl-rev-customer"><div className="mdl-rev-avatar">{r[0]}</div><div className="mdl-rev-info"><h4 className="mdl-rev-name">{r[1]} <span className="mdl-rev-verified" title="Verified Buyer">✓</span></h4><p className="mdl-rev-location">{r[2]}</p></div></div></article>)}</div><div className="mdl-rev-controls mdl-anim-rev"><button className="mdl-rev-arrow" onClick={()=>move(-1)} aria-label="Previous Review">←</button><button className="mdl-rev-arrow" onClick={()=>move(1)} aria-label="Next Review">→</button></div></div></section>}
export function LocationFaq(){return <section className="mdl-location-faq-safe"><div className="mdl-lf-wrap-safe"><div className="mdl-lf-map-card-safe"><h3 className="mdl-lf-map-heading-safe">Our Location</h3><div className="mdl-lf-map-frame-safe"><iframe title="MD Latex location" src="https://www.google.com/maps?q=MD+Latex+HQ,+17,+Jalan+SBC+5,+Kawasan+Industri+Batu+Caves,+68100+Batu+Caves,+Selangor&output=embed" loading="lazy" referrerPolicy="no-referrer-when-downgrade"/></div></div><div className="mdl-lf-faq-card-safe"><h3 className="mdl-lf-faq-heading-safe">Frequently Asked Questions</h3><div className="mdl-lf-faq-list-safe">{faqs.map(f=><details className="mdl-lf-faq-item-safe" key={f[0]}><summary className="mdl-lf-faq-summary-safe"><span className="mdl-lf-faq-logo-safe"><img src="https://cdn.shopify.com/s/files/1/0832/5038/1050/files/image.png?v=1779189365" alt="MD Latex"/></span><span className="mdl-lf-faq-q-text-safe">{f[0]}</span><span className="mdl-lf-faq-chevron-safe">⌄</span></summary><div className="mdl-lf-faq-answer-safe">{f[1]}</div></details>)}</div></div></div></section>}
const fits=[['Mattresses','mattresses','https://mdlatex.com.my/cdn/shop/collections/1_f430e1ac-d540-4a5c-9fdf-c44aaa4ef0bc.png?v=1784705454&width=1500'],['Pillows','pillows','https://mdlatex.com.my/cdn/shop/collections/2_586fe363-0b3d-42bd-a175-5305eba32605.png?v=1784705456&width=1500'],['Baby & Kids','baby-kids','https://mdlatex.com.my/cdn/shop/collections/3_85b736eb-70f5-4f64-a8b0-2fdcedfa9874.png?v=1784705452&width=1500']];
export function PerfectFit(){const rail=useRef<HTMLDivElement>(null);const[index,setIndex]=useState(0);const go=(next:number)=>{const value=Math.max(0,Math.min(2,next));setIndex(value);const card=rail.current?.querySelector<HTMLElement>('.category');rail.current?.scrollTo({left:value*((card?.offsetWidth||335)+10),behavior:'smooth'})};return <section className="section categories perfect-fit"><h2>Find the Perfect Fit for Your Needs</h2><div className="category-grid" ref={rail} onScroll={()=>{const card=rail.current?.querySelector<HTMLElement>('.category');if(card)setIndex(Math.min(2,Math.round((rail.current?.scrollLeft||0)/(card.offsetWidth+10))))}}>{fits.map(c=><Link href={`/collections/${c[1]}`} className="category" key={c[1]}><img src={c[2]} alt={c[0]}/><span>{c[0]} <b>→</b></span></Link>)}</div><div className="fit-controls"><button onClick={()=>go(index-1)} disabled={index===0} aria-label="Previous category">‹</button><span>{index+1}/3</span><button onClick={()=>go(index+1)} disabled={index===2} aria-label="Next category">›</button></div></section>}
